//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotBadge.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotBadge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; width=&quot;{0}&quot; height=&quot;20&quot;&gt;
        ///  &lt;linearGradient id=&quot;b&quot; x2=&quot;0&quot; y2=&quot;100%&quot;&gt;
        ///    &lt;stop offset=&quot;0&quot; stop-color=&quot;#bbb&quot; stop-opacity=&quot;.1&quot;/&gt;
        ///    &lt;stop offset=&quot;1&quot; stop-opacity=&quot;.1&quot;/&gt;
        ///  &lt;/linearGradient&gt;
        ///  &lt;mask id=&quot;a&quot;&gt;
        ///    &lt;rect width=&quot;{0}&quot; height=&quot;20&quot; rx=&quot;3&quot; fill=&quot;#fff&quot;/&gt;
        ///  &lt;/mask&gt;
        ///  &lt;g mask=&quot;url(#a)&quot;&gt;
        ///    &lt;path fill=&quot;#555&quot; d=&quot;M0 0h{1}v20H0z&quot;/&gt;
        ///	  &lt;path fill=&quot;{7}&quot; d=&quot;M{1} 0h{2}v20H{1}z&quot;/&gt;
        ///	  &lt;path fill=&quot;url(#b)&quot; d=&quot;M0 0h{0}v20H0z&quot;/&gt;
        ///  &lt;/g&gt;
        ///  &lt;g fill=&quot;#fff&quot; text-anchor= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string flat {
            get {
                return ResourceManager.GetString("flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; width=&quot;{0}&quot; height=&quot;20&quot;&gt;
        ///  &lt;g shape-rendering=&quot;crispEdges&quot;&gt;
        ///    &lt;path fill=&quot;#555&quot; d=&quot;M0 0h{1}v20H0z&quot;/&gt;
        ///    &lt;path fill=&quot;{7}&quot; d=&quot;M{1} 0h{2}v20H{1}z&quot;/&gt;
        ///  &lt;/g&gt;
        ///  &lt;g fill=&quot;#fff&quot; text-anchor=&quot;middle&quot; font-family=&quot;DejaVu Sans,Verdana,Geneva,sans-serif&quot; font-size=&quot;11&quot;&gt;
        ///    &lt;text x=&quot;{3}&quot; y=&quot;14&quot;&gt;{5}&lt;/text&gt;
        ///    &lt;text x=&quot;{4}&quot; y=&quot;14&quot;&gt;{6}&lt;/text&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string flatSquare {
            get {
                return ResourceManager.GetString("flatSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; width=&quot;{0}&quot; height=&quot;18&quot;&gt;
        ///  &lt;linearGradient id=&quot;b&quot; x2=&quot;0&quot; y2=&quot;100%&quot;&gt;
        ///    &lt;stop offset=&quot;0&quot; stop-color=&quot;#fff&quot; stop-opacity=&quot;.7&quot;/&gt;
        ///    &lt;stop offset=&quot;.1&quot; stop-color=&quot;#aaa&quot; stop-opacity=&quot;.1&quot;/&gt;
        ///    &lt;stop offset=&quot;.9&quot; stop-opacity=&quot;.3&quot;/&gt;
        ///    &lt;stop offset=&quot;1&quot; stop-opacity=&quot;.5&quot;/&gt;
        ///  &lt;/linearGradient&gt;
        ///  &lt;mask id=&quot;a&quot;&gt;
        ///    &lt;rect width=&quot;{0}&quot; height=&quot;18&quot; rx=&quot;4&quot; fill=&quot;#fff&quot;/&gt;
        ///  &lt;/mask&gt;
        ///  &lt;g mask=&quot;url(#a)&quot;&gt;
        ///    &lt;path fill=&quot;#555&quot; d=&quot;M0 0h{1}v18H0z&quot;/&gt;
        ///    &lt;path fill=&quot;{7}&quot; d=&quot;M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plastic {
            get {
                return ResourceManager.GetString("plastic", resourceCulture);
            }
        }
    }
}
